### PR TITLE
Upstream merge to make new revision of PortaPack work

### PR DESCRIPTION
**Pull request by Maescool**
I've received a new revision of the PortaPack, which has a new clock, 
now this clock requires some changes to the code, cause I could load the havoc, but i would lock up.
so I've merged Jared's changes to the havoc branch, and seems more stable now, and it looks like things are working (haven't done a full feature test run, just some simple tests)
(this merge has not yet been tested on older version)

### CODE REVIEW

**Comment by TheCranston** [comment]
@Maescool Happy new year.  I think my build chain is not correct.  Can you provide a binary for testing of your merged changes?  I've been using the binary that jboone posted of his changes and it's been working great for me.  Love to test it with havoc.  thanks.

**Comment by ryanrohypnol** [comment]
I just ordered the Portapack, so I'm assuming I have the new version. I did not try to install the havoc firmware yet so I'll just wait for you to release a binary <3 

Thank you

**Comment by unixpunk** [comment]
I can confirm that this change does NOT work on the older portapack.  I don't mind testing future attempts for a unified code-base among portapack models but as far as havoc goes, I'm stuck at bbb5dc3 until resolved.  Thanks for the work here, btw!

**Comment by Maescool** [comment]
Yes, this was not supposed to be merged yet, I did some initial tests on the new release of Portapack, however, didn't test on the older model yet at time of sending this request, did figure out later it was not compatible, as I posted I hadn't tested that one yet, but I see jboone has made a better fix.

**Comment by jboone** [comment]
@Maescool Thanks for the initial merge work. It turned out to be a lot more work than I'd expected. It took a couple of weeks to work through all the issues I'd found. I'm glad though that everything seems resolved and several users are reporting success. I should ship a release soon.

**Pull request merged**
