### PR TITLE
Update ui_scanner.cpp

### PR DESCRIPTION
**Pull request by bicurico**
This replaces the static list of frequencies with a routine that reads file "scanner-freq.TXT" from SDCARD (root).
The file contains one frequency per line, which needs to have 10 digits and end in CrLf (Windows style).
The last line has to contain "ENDENDENDE"+ CrLf.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
> end in CrLf (Windows style).

What about users not running Windows?

**Comment by bicurico** [comment]
I think you would just need to use the UNIX2DOS conversion tool.

It should be included in most shells.

The thing is that reading in a file is done in binary mode and to decode each line, I need to know exactly how many bytes it has. Because I only use Windows, each line has 10 bytes for the frequency and then a CrLf, which adds to a total of 12 bytes. If you would save the file in UNIX format, each line only has 11 bytes and the read routine would mess up the frequency values.

Further information with information how to convert between UNIX and DOS:

https://en.wikipedia.org/wiki/Unix2dos
https://kb.iu.edu/d/acux

Regards,
Vitor

De: AsciiWolf <notifications@github.com>
Enviada: 17 September 2019 11:27
Para: furrtek/portapack-havoc <portapack-havoc@noreply.github.com>
Cc: Vitor Martins Augusto <vma@norcam.pt>; Author <author@noreply.github.com>
Assunto: Re: [furrtek/portapack-havoc] Update ui_scanner.cpp (#266)


end in CrLf (Windows style).

What about users not running Windows?

**Comment by spm81** [comment]
Hi there 
Can you leave a sample scanner-freq.TXT file?

**Comment by bicurico** [comment]
[scanner-freq.TXT](https://github.com/furrtek/portapack-havoc/files/3683395/scanner-freq.TXT)
Here you go...

**Comment by bicurico** [comment]
[portapack-h1-havoc-vma.zip](https://github.com/furrtek/portapack-havoc/files/3683400/portapack-h1-havoc-vma.zip)

This is the last version I made, which adds the scanner using the frequency file and corrects the PLAY DEAD function.

**Comment by z4ziggy** [comment]
https://github.com/z4ziggy/portapack-havoc/commit/a32c65fb4a2b789acbe0ad0ea392fb69099783c4

tnx for the idea.

**Pull request closed without merging**
