### PR TITLE
UI Redesign for Portapack-Havoc

### PR DESCRIPTION
**Pull request by z4ziggy**
SCR_0004

### CODE REVIEW

**Comment by jLynx** [comment]
Is it possible to have this as a toggle in the setting?

**Comment by z4ziggy** [comment]
> Is it possible to have this as a toggle in the setting?

not worth the hassle.

**Comment by z4ziggy** [comment]
tnx for the merge :)
I've closed it since I thought the jboone patches I've merged are too much for this pull req. Glad you added the hackrf repo - it makes the (re)build much faster.

**Comment by scorpionul222** [comment]
Hello compile not work error libopencm3_hackrf_usb.dir

**Comment by scorpionul222** [comment]
And cmake error hackrf/firmware/hackrf_usb

**Comment by furrtek** [comment]
`git submodule update --init --recursive`

PS: There's an edit button.

**Comment by YannickDC** [comment]
Would there be a way to revert back to the old menu?

**Pull request merged**
