### PR TITLE
PortaPack Sync

### PR DESCRIPTION
**Pull request by jboone**
This pull request brings HAVOC pretty much up-to-date with the PortaPack repository. However, it was made to the commit before @Maescool. I would recommend reverting that pull request and applying this one, as there will be damage if trying to incorporate commits from the other pull request.

This PR was quickly confirmed to be functional on all versions of the PortaPack hardware.

### CODE REVIEW

**Comment by jboone** [comment]
To be more clear, all conflicts in this pull request should be resolved in favor of this PR, or badness will happen.

**Comment by TheCranston** [comment]
@jboone Thank you for the work on this.  I tried to build a binary from this pull request.  Initial experience is that the havoc mode is working.   I get this really cool image on the screen in HackRF mode:
img_1462

Something changed in the device entries and I'm having a great amount of difficulty with apps that rely on the Soapy layer to communicate with the HackRF..  So I can get gqrx to work, but not cubicSDR, for instance.  hackrf cli utilities work fine.

**Comment by jboone** [comment]
I'm going to see if I can't clean up this PR and make it apply cleanly. It'll involve reverting the @Maescool PR, cherry-picking the AIS map view commit into my "portapack_sync" branch, then merging to master. Wish me luck!

**Comment by TheCranston** [comment]
:) Good Luck

**Comment by jboone** [comment]
@TheCranston The display during HackRF mode is very much expected and intended. :-)

I'm closing this, as it's now a stale pull request. I have a new PR open that @furrtek should be able to merge more easily, pull request #215.

I'm surprised to hear you're having trouble with your PC-based software. I have a build binary from Travis-CI you can test, in case your build environment is somehow problematic:

https://portapack-h1-builds.s3.amazonaws.com/jboone/portapack-havoc/3/3.1/build/firmware/portapack-h1-havoc-b4ccefa.tar.bz2

Please report on the other pull request what operating system you're using, what expected and actual behavior you're seeing from your PC-based tools, etc. All detail you can provide will help!

**Pull request closed without merging**
